language: android
sudo: false
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    # The BuildTools version used by your project
    #- build-tools-19.1.0

    # The SDK version used to compile your project
    - android-25

    # Additional components
      - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
      - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25
jdk: oraclejdk8
os:
  - linux
